src/GOORRRNG/천성준/DFS/백준-1024 유기농 배추/유기농 배추.md
=> TEST:PR 테스트

src/GOORRRNG/공태현/simulation/비밀번호/비밀번호.java, src/GOORRRNG/공태현/simulation/비밀번호/비밀번호.md
=> 구현, 시뮬레이션: 비밀번호

src/GOORRRNG/최민지/bfs/게임 맵 최단거리/게임 맵 최단거리.java, src/GOORRRNG/최민지/bfs/게임 맵 최단거리/게임 맵 최단거리.md
=> BFS: 게임 맵 최단거리

src/GOORRRNG/공태현/dfs/가장_가까운_큰수/가장 가까운 큰수.md, src/GOORRRNG/공태현/dfs/가장_가까운_큰수/가장_가까운_큰수.java
=> solved: 가장 가까운 큰수(DFS, 백트래킹)

src/GOORRRNG/공태현/dfs/바둑대회/바둑대회.java, src/GOORRRNG/공태현/dfs/바둑대회/바둑대회.md
커밋 실수로 그냥 커밋을 되돌리지 않고 push 하는 파일로 이전 파일을 업데이트 했습니다. 커밋이 많다고 신경쓰지 않으셔도 됩니다. repository에는 아무 이상 없습니다.
=> solved: 바둑대회(DFS)

src/GOORRRNG/공태현/dfs/팰린드롬_경우수/팰린드롬 경우수.md, src/GOORRRNG/공태현/dfs/팰린드롬_경우수/팰린드롬_경우수.java
=> solved: 팰린드롬 경우수(DFS)

src/GOORRRNG/공태현/bfs/타일_점프/타일 점프.md, src/GOORRRNG/공태현/bfs/타일_점프/타일_점프.java
=> solved: 타일 점프(BFS)

src/GOORRRNG/최민지/bfs/Rotting Oranges/RottingOranges.java, src/GOORRRNG/최민지/bfs/Rotting Oranges/RottingOranges.md
LeetCode 문제입니다. 
https://leetcode.com/problems/rotting-oranges/description/
=> solved: Rotting Oranges(bfs)

src/GOORRRNG/공태현/bfs/집을_짓자/집을 짓자.md, src/GOORRRNG/공태현/bfs/집을_짓자/집을_짓자.java
=> solved: 집을 짓자(BFS)

src/GOORRRNG/공태현/bfs/숲속의_기사/숲속의 기사.md, src/GOORRRNG/공태현/bfs/숲속의_기사/숲속의_기사.java
=> solved: 숲속의 기사(BFS)

src/GOORRRNG/최민지/dp/StoneGameVIII/StoneGameVIII.java, src/GOORRRNG/최민지/dp/StoneGameVIII/StoneGameVIII.md
=> solved: Stone Game VIII

src/GOORRRNG/최민지/bfs/전력망을_둘로_나누기/전력망을_둘로_나누기.java, src/GOORRRNG/최민지/bfs/전력망을_둘로_나누기/전력망을_둘로_나누기.md
=> solved: 전력망을 둘로 나누기 (bfs)

src/GOORRRNG/최민지/dfs/Combination_Sum_III/Combination_Sum_III.java, src/GOORRRNG/최민지/dfs/Combination_Sum_III/Combination_Sum_III.md
=> solved: Combination Sum III (dfs, backtracking)

src/GOORRRNG/최민지/구현/Basic_Calculator/Basic_Calculator.java, src/GOORRRNG/최민지/구현/Basic_Calculator/Basic_Calculator.md
=> solved: Basic Calculator (구현)

src/GOORRRNG/이다솜/브루트포스/체스판_다시_칠하기/Main.java, src/GOORRRNG/이다솜/브루트포스/체스판_다시_칠하기/README.md
=> solved: 체스판 다시 칠하기(브루트포스)

src/GOORRRNG/이다솜/해쉬/문자열_집합/Main.java, src/GOORRRNG/이다솜/해쉬/문자열_집합/README.md
=> solved: 문자열 집합(해쉬)

src/GOORRRNG/최민지/dfs/Word_Search/Word_Search.java, src/GOORRRNG/최민지/dfs/Word_Search/Word_Search.md
=> solved: Word Search (dfs, backtracking)

src/GOORRRNG/최민지/dp/Min_Cost_Climbing_Stairs/Min_Cost_Climbing_Stairs.java, src/GOORRRNG/최민지/dp/Min_Cost_Climbing_Stairs/Min_Cost_Climbing_Stairs.md
=> solved: Min Cost Climbing Stairs (dp)

src/GOORRRNG/최민지/dp/Domino_and_Tromino_Tiling/Domino_and_Tromino_Tiling.java, src/GOORRRNG/최민지/dp/Domino_and_Tromino_Tiling/Domino_and_Tromino_Tiling.md
=> solved: Domino and Tromino Tiling (dp)

src/GOORRRNG/최민지/bfs/아이템줍기/아이템줍기.java, src/GOORRRNG/최민지/bfs/아이템줍기/아이템줍기.md
=> solved: 아이템 줍기 (bfs)

src/GOORRRNG/최민지/heap/Total_Cost_to_Hire_K_Workers/Total_Cost_to_Hire_K_Workers.java, src/GOORRRNG/최민지/heap/Total_Cost_to_Hire_K_Workers/Total_Cost_to_Hire_K_Workers.md
=> solved: Total Cost to Hire K Workers (heap)

src/GOORRRNG/최민지/이분탐색/Find_Peak_Element/Find_Peak_Element.java, src/GOORRRNG/최민지/이분탐색/Find_Peak_Element/Find_Peak_Element.md
=> solved: Find Peak Element (이분팀색)

src/GOORRRNG/최민지/dp/Longest_Common_Subsequence/Longest_Common_Subsequence.java, src/GOORRRNG/최민지/dp/Longest_Common_Subsequence/Longest_Common_Subsequence.md
=> solved: Longest Common Subsequence (dp)

src/GOORRRNG/최민지/dp/2xn타일링/2xn타일링.java, src/GOORRRNG/최민지/dp/2xn타일링/2xn타일링.md
=> solved: 2 x n 타일링 (dp)
